language: rust
rust:
    - nightly
    - stable
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libopenal-dev libsndfile1-dev libasound2-dev
script:
    - cargo build --verbose --all
    - cargo test --verbose --all
