[package]
name = "gentle-ap-physics-rs"
version = "0.1.0"
authors = ["Tanay Nathan <tnathan@berkeley.edu>"]

[dependencies]
rayon-hash = "0.4.1"
criterion = "0.1.2"

[[bench]]
name = "vector3_benchmark"
harness = false


