[package]
name = "gentle-ap-physics-rs"
version = "0.1.0"
authors = ["Tanay Nathan <tanaynathan14@gmail.com>", "Gabriel Gardner", "Krishnan Rajiyah"]

[dependencies]
rayon-hash = "0.4.1"
three = "0.4.0"
